language: node_js
sudo: false
node_js:
- '0.12'
- '4'
- '5'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - secure: Wq/jzSGq7+g0f9j7MH8IaQBG9HRMvJskqdXb6VppaaxNjzFG2IY/ayMBUQMa7NH8l8JWIA4wCWvsJ0Azcqd2rO2jsbKDWbGYtK1WMrPioM6xWAaJ2iMsdgtwakhroIS9wD5faKbWoHjs3dYbK/f3N2dN1dJSZKVAicpW0JEZMeQ=
  - secure: gZ5jZd+M3EUjliiq41gs6S9dxke8Rh8jUlTxiGSeJWST22VZh8x5ZjHAZyr/zIJqjmfMngHU25akZF9CPBS7dixAGAVOr8jH6DxFg4APo8CNyl+g4oqOFvOL6iEBkV9drH9y2hr8CTz6MHOtwfoZU6uuQAhxcmfRG6wTxnUiipE=
